# Generated by Django 3.2.16 on 2023-01-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('carbohydrate', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('province', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('total_calorie', models.IntegerField(default=0)),
                ('ingredient', models.JSONField(default=list)),
                ('recipe', models.TextField(default='')),
                ('tip', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('carbohydrate', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('province', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('total_calorie', models.IntegerField(default=0)),
                ('ingredient', models.JSONField(default=list)),
                ('recipe', models.TextField(default='')),
                ('tip', models.TextField(default='')),
                ('carbohydrate_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidedata_carbohydrate_type', to='diet.filter')),
                ('flavor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidedata_flavor', to='diet.filter')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidedata_type', to='diet.filter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
