# Generated by Django 3.2.16 on 2023-01-17 18:05

import diet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='image_selected',
            field=models.ImageField(default='default1.jpg', upload_to=diet.models.articles_image_path),
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='query_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='data',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='province',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='salt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sidedata',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sidedata',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sidedata',
            name='province',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sidedata',
            name='salt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sidedata',
            name='total_calorie',
            field=models.FloatField(default=0),
        ),
    ]
