# Generated by Django 3.2.16 on 2023-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietAllergy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='', max_length=20)),
                ('updated_by', models.CharField(default='', max_length=20)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
