# Generated by Django 3.2.16 on 2023-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietallergy'),
        ('user', '0002_auto_20230110_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.AddField(
            model_name='data',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mainside',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mainside',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sidedata',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sidedata',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
