# Generated by Django 3.2.16 on 2023-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20230110_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='filter_category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='filter',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
