version: '3'
services:
  web:
    container_name: web
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: eatda_be.settings.dev
      TZ: "Asia/Seoul"
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  app:
