# Generated by Django 3.2.16 on 2023-01-11 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('id', models.PositiveIntegerField(choices=[(0, 'Mom'), (1, 'Dad'), (2, 'Brother1'), (3, 'Brother2'), (4, 'Brother3')], primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('name', models.CharField(max_length=20)),
                ('height', models.FloatField(default=None, null=True)),
                ('weight', models.FloatField(default=None, null=True)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('is_diabetes', models.BooleanField(default=False)),
                ('activity', models.IntegerField(choices=[(-1, 'Nochoices'), (0, 'Deeplow'), (1, 'Low'), (2, 'Middle'), (3, 'High'), (4, 'Deephigh')], default=-1)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.character')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.dietallergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('react', models.IntegerField(choices=[(0, 'Heart'), (1, 'Smile'), (2, 'Sad')], default=0)),
                ('target', models.IntegerField(choices=[(0, 'Todaydiet'), (1, 'Afterblood')])),
                ('timeline', models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Night')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloodSugarLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('level', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('timeline', models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Night')])),
                ('diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.data')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
