# Generated by Django 3.2.16 on 2023-01-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietallergy'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='', max_length=20)),
                ('updated_by', models.CharField(default='', max_length=20)),
                ('allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.dietallergy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bloodsugarlevel',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodsugarlevel',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='info',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='info',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='like',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ourpick',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ourpick',
            name='updated_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.info'),
        ),
    ]
