# Generated by Django 3.2.16 on 2023-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230115_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsugarlevel',
            name='time',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='character',
            field=models.IntegerField(choices=[(0, 'Mom'), (1, 'Dad'), (2, 'Brother1'), (3, 'Brother2'), (4, 'Brother3')]),
        ),
    ]
