# Generated by Django 3.2.16 on 2023-01-20 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230117_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='info',
            name='amr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='bmr',
            field=models.FloatField(default=None, null=True),
        ),
    ]
